### ISSUE TITLE
How to multiline panel content

### ISSUE THREAD

**Issue by pashute** [munsterlander/Onsen-Examples#1]
I have multiline panel content. How do I do this? 

The following shows the text on a single line!

    <ons-list-item tappable class="accordion" onclick="accord(this)">&nbsp;Item 2</ons-list-item>
          <div class="panel"><ons-list-item tappable>
               <p>Item 2 Details</p><br />
               <p>bli bli bli </p>
               <p>third line</p>
               <p>4th line</p>
               <p>5th line</p>
             </ons-list-item>
          </div>
          <ons-list-item tappable class="accordion" onclick="accord(this)">&nbsp;Item 3</ons-list-item>
          <div class="panel"><ons-list-item tappable>
               <p>item 3 Details</p>
               <p>bla blo blu</p>
               <p>third line</p>
             </ons-list-item>
         </div>

Also, the content text always starts way down. Is there anything I can do have it show immediately below?

**Comment by pashute** [comment]
Your sample html code in the readme has a mistakes. What was intended?
1. An unclosed ons-list-item 
2. Missing several collapsable items to show the sample accordion correctly:

     ```
    <!-- row 1 has OLI (ons-list-item) opened and closed -->
    <ons-list-item tappable class="accordion" onclick="fn.toggle(this)">Items</ons-list-item>
       <div class="panel">
               <!-- next rows 3-6 have closed OLI on each row inside the toggled panel -->
           <ons-list-item tappable>Item 1</ons-list-item>
           <ons-list-item tappable>Item 2</ons-list-item>
           <ons-list-item tappable>Item 3</ons-list-item>
           <ons-list-item tappable>Item 4</ons-list-item>         
       </div>
     <!-- next line has a close OLI.  is that just a mistake?  I'm trying to understand... -->
     </ons-list-item>
      ```

Or would the following be a valid example?

    <ons-list-item tappable class="accordion" onclick="fn.toggle(this)">Heading 1</ons-list-item>
    <div class="panel">
       <ons-list-item tappable>Details1 Item 1</ons-list-item>
       <ons-list-item tappable>Details1 Item 2</ons-list-item>
      <ons-list-item tappable>Details1 Item 3</ons-list-item>
       <ons-list-item tappable>Details1 Item 4</ons-list-item>         
    </div>
    <ons-list-item tappable class="accordion" onclick="fn.toggle(this)">Heading 2</ons-list-item>
    <div class="panel">
       <ons-list-item tappable>Details2 Item 1</ons-list-item>
       <ons-list-item tappable>Details2Item 2</ons-list-item>
       <ons-list-item tappable>Details2 Item 3</ons-list-item>
       <ons-list-item tappable>Details2 Item 4</ons-list-item>         
    </div>

**Comment by munsterlander** [comment]
Did you ever get this going?  I would need to go back and look, but I believe the first line should not have the closing ons-list-item tag.  Additionally, you will have to override the default list-item CSS to make it multiline probably.  There have been too many changes to Onsen to keep these examples updated.
